#!/system/bin/sh

###################################
# Common Function
###################################

perfcommon() {
	# Disable Kernel panic
	apply 0 /proc/sys/kernel/panic
	apply 0 /proc/sys/kernel/panic_on_oops
	apply 0 /proc/sys/kernel/panic_on_warn
	apply 0 /proc/sys/kernel/softlockup_panic

	# Sync to data in the rare case a device crashes
	sync

	# Push Notification
	su -lp 2000 -c "/system/bin/cmd notification post -t 'EronX | Bypass Charging' -i file:///data/local/tmp/bypass_chg_logo.png -I file:///data/local/tmp/bypass_chg_logo.png 'bypass_chg' 'Bypass mode activated'" >/dev/null &

	# I/O Tweaks
	for dir in /sys/block/mmcblk0 /sys/block/mmcblk1 /sys/block/sd*; do
		# Disable I/O statistics accounting
		apply 0 "$dir/queue/iostats"

		# Reduce the maximum number of I/O requests in exchange for latency
		apply 64 "$dir/queue/nr_requests"

		# Don't use I/O as random spice
		apply 0 "$dir/queue/add_random"
	done &

	# Networking tweaks
	if grep -q bbr2 /proc/sys/net/ipv4/tcp_available_congestion_control; then
		apply "bbr2" /proc/sys/net/ipv4/tcp_congestion_control
	else
		apply "cubic" /proc/sys/net/ipv4/tcp_congestion_control
	fi

	apply "1" /proc/sys/net/ipv4/tcp_low_latency
	apply "1" /proc/sys/net/ipv4/tcp_ecn
	apply "3" /proc/sys/net/ipv4/tcp_fastopen
	apply "1" /proc/sys/net/ipv4/tcp_sack
	apply "0" /proc/sys/net/ipv4/tcp_timestamps

	# Stop tracing and debugging
	if [ "$(cat /data/bypass_chg/kill_logd)" -eq 1 ]; then
		apply 0 /sys/kernel/ccci/debug
		apply 0 /sys/kernel/tracing/tracing_on
		apply 0 /proc/sys/kernel/perf_event_paranoid
		apply 0 /proc/sys/kernel/debug_locks
		apply 0 /proc/sys/kernel/perf_cpu_time_max_percent
		apply off /proc/sys/kernel/printk_devkmsg
		stop logd
		stop traced
		stop statsd
	fi

	# Disable schedstats
	apply 0 /proc/sys/kernel/sched_schedstats

	# Disable Oppo/Realme cpustats
	apply 0 /proc/sys/kernel/task_cpustats_enable

	# Disable Sched auto group
	apply 0 /proc/sys/kernel/sched_autogroup_enabled

	# Enable CRF
	apply 1 /proc/sys/kernel/sched_child_runs_first

	# Improve real time latencies by reducing the scheduler migration time
	apply 32 /proc/sys/kernel/sched_nr_migrate

	# Tweaking scheduler to reduce latency
	apply 50000 /proc/sys/kernel/sched_migration_cost_ns
	apply 1000000 /proc/sys/kernel/sched_min_granularity_ns
	apply 1500000 /proc/sys/kernel/sched_wakeup_granularity_ns

	# Disable read-ahead for swap devices
	apply 0 /proc/sys/vm/page-cluster

	# Update /proc/stat less often to reduce jitter
	apply 120 /proc/sys/vm/stat_interval

	# Disable compaction_proactiveness
	apply 0 /proc/sys/vm/compaction_proactiveness

	# Disable SPI CRC
	apply 0 /sys/module/mmc_core/parameters/use_spi_crc

	# Disable OnePlus opchain
	apply 0 /sys/module/opchain/parameters/chain_on

	# Disable Oplus bloats
	apply 0 /sys/module/cpufreq_bouncing/parameters/enable
	apply 0 /proc/task_info/task_sched_info/task_sched_info_enable
	apply 0 /proc/oplus_scheduler/sched_assist/sched_assist_enabled

	# Report max CPU capabilities to these libraries
	apply "libunity.so, libil2cpp.so, libmain.so, libUE4.so, libgodot_android.so, libgdx.so, libgdx-box2d.so, libminecraftpe.so, libLive2DCubismCore.so, libyuzu-android.so, libryujinx.so, libcitra-android.so, libhdr_pro_engine.so, libandroidx.graphics.path.so, libeffect.so" /proc/sys/kernel/sched_lib_name
	apply 255 /proc/sys/kernel/sched_lib_mask_force

	# Let Encore control anything without FPSGO
	apply 0 /sys/kernel/fpsgo/common/fpsgo_enable

	# Set thermal governor to step_wise
	for dir in /sys/class/thermal/thermal_zone*; do
		apply "step_wise" $dir/policy
	done
}

performance_profile() {
	[ "$(cat /data/bypass_chg/bypass_charging)" -eq 1 ] && bypass_chg_utility enable_bypass_chg
	[ "$(cat /data/bypass_chg/dnd_gameplay)" -eq 1 ] && bypass_chg_utility set_dnd priority

	# Disable battery saver module
	[ -f /sys/module/battery_saver/parameters/enabled ] && {
		if grep -qo '[0-9]\+' /sys/module/battery_saver/parameters/enabled; then
			apply 0 /sys/module/battery_saver/parameters/enabled
		else
			apply N /sys/module/battery_saver/parameters/enabled
		fi
	}

	# Disable split lock mitigation
	apply 0 /proc/sys/kernel/split_lock_mitigate

	if [ -f "/sys/kernel/debug/sched_features" ]; then
		# Consider scheduling tasks that are eager to run
		apply NEXT_BUDDY /sys/kernel/debug/sched_features

		# Some sources report large latency spikes during large migrations
		apply NO_TTWU_QUEUE /sys/kernel/debug/sched_features
	fi

	if [ -d "/dev/stune/" ]; then
		# Prefer to schedule top-app tasks on idle CPUs
		apply 1 /dev/stune/top-app/schedtune.prefer_idle

		# Mark top-app as boosted, find high-performing CPUs
		apply 1 /dev/stune/top-app/schedtune.boost
	fi

	# Oppo/Oplus/Realme Touchpanel
	tp_path="/proc/touchpanel"
	if [ -d tp_path ]; then
		apply "1" $tp_path/game_switch_enable
		apply "0" $tp_path/oplus_tp_limit_enable
		apply "0" $tp_path/oppo_tp_limit_enable
		apply "1" $tp_path/oplus_tp_direction
		apply "1" $tp_path/oppo_tp_direction
	fi

	# Memory tweak
	apply 80 /proc/sys/vm/vfs_cache_pressure

	# eMMC and UFS governor
	for path in /sys/class/devfreq/*.ufshc; do
		apply performance $path/governor
	done &
	for path in /sys/class/devfreq/mmc*; do
		apply performance $path/governor
	done &

	# I/O Tweaks
	for dir in /sys/block/mmcblk0 /sys/block/mmcblk1 /sys/block/sd*; do
		# Reduce heuristic read-ahead in exchange for I/O latency
		apply 32 "$dir/queue/read_ahead_kb"
	done &

	case "$(cat /data/bypass_chg/soc_recognition)" in
	1) mediatek_performance ;;
	2) snapdragon_performance ;;
	3) exynos_performance ;;
	4) unisoc_performance ;;
	5) tensor_performance ;;
	6) intel_performance ;;
	7) tegra_performance ;;
	esac

	echo 3 >/proc/sys/vm/drop_caches
}

normal_profile() {
	[ "$(cat /data/bypass_chg/bypass_charging)" -eq 1 ] && bypass_chg_utility disable_bypass_chg
	[ "$(cat /data/bypass_chg/dnd_gameplay)" -eq 1 ] && bypass_chg_utility set_dnd off

	if [ -f /data/bypass_chg/custom_default_cpu_gov ]; then
		default_cpu_gov=$(cat /data/bypass_chg/custom_default_cpu_gov)
	else
		default_cpu_gov=$(cat /data/bypass_chg/default_cpu_gov)
	fi

	# Disable battery saver module
	[ -f /sys/module/battery_saver/parameters/enabled ] && {
		if grep -qo '[0-9]\+' /sys/module/battery_saver/parameters/enabled; then
			apply 0 /sys/module/battery_saver/parameters/enabled
		else
			apply N /sys/module/battery_saver/parameters/enabled
		fi
	}

	# Enable split lock mitigation
	apply 1 /proc/sys/kernel/split_lock_mitigate

	if [ -f "/sys/kernel/debug/sched_features" ]; then
		# Consider scheduling tasks that are eager to run
		apply NEXT_BUDDY /sys/kernel/debug/sched_features

		# Schedule tasks on their origin CPU if possible
		apply TTWU_QUEUE /sys/kernel/debug/sched_features
	fi

	if [ -d "/dev/stune/" ]; then
		# We are not concerned with prioritizing latency
		apply 0 /dev/stune/top-app/schedtune.prefer_idle

		# Mark top-app as boosted, find high-performing CPUs
		apply 1 /dev/stune/top-app/schedtune.boost
	fi

	# Oppo/Oplus/Realme Touchpanel
	tp_path="/proc/touchpanel"
	if [ -d tp_path ]; then
		apply "0" $tp_path/game_switch_enable
		apply "1" $tp_path/oplus_tp_limit_enable
		apply "1" $tp_path/oppo_tp_limit_enable
		apply "0" $tp_path/oplus_tp_direction
		apply "0" $tp_path/oppo_tp_direction
	fi

	# Memory Tweaks
	apply 120 /proc/sys/vm/vfs_cache_pressure

	# eMMC and UFS governor
	for path in /sys/class/devfreq/*.ufshc; do
		apply simple_ondemand $path/governor
	done &
	for path in /sys/class/devfreq/mmc*; do
		apply simple_ondemand $path/governor
	done &

	# Restore min CPU frequency
	change_cpu_gov "$default_cpu_gov"
	apply 1 /sys/devices/system/cpu/cpu1/online
	chmod -f 644 /sys/devices/virtual/thermal/thermal_message/cpu_limits

	if [ -d /proc/ppm ]; then
		cluster=0
		for path in /sys/devices/system/cpu/cpufreq/policy*; do
			cpu_maxfreq=$(cat $path/cpuinfo_max_freq)
			cpu_minfreq=$(cat $path/cpuinfo_min_freq)
			apply "$cluster $cpu_maxfreq" /proc/ppm/policy/userlimit_max_cpu_freq
			apply "$cluster $cpu_minfreq" /proc/ppm/policy/userlimit_min_cpu_freq
			((cluster++))
		done
	fi

	for path in /sys/devices/system/cpu/*/cpufreq; do
		cpu_maxfreq=$(cat $path/cpuinfo_max_freq)
		cpu_minfreq=$(cat $path/cpuinfo_min_freq)
		apply "$cpu_maxfreq" $path/scaling_max_freq
		apply "$cpu_minfreq" $path/scaling_min_freq
	done

	# I/O Tweaks
	for dir in /sys/block/mmcblk0 /sys/block/mmcblk1 /sys/block/sd*; do
		# Reduce heuristic read-ahead in exchange for I/O latency
		apply 128 "$dir/queue/read_ahead_kb"
	done &

	case "$(cat /data/bypass_chg/soc_recognition)" in
	1) mediatek_normal ;;
	2) snapdragon_normal ;;
	3) exynos_normal ;;
	4) unisoc_normal ;;
	5) tensor_normal ;;
	6) intel_normal ;;
	7) tegra_normal ;;
	esac
}

powersave_profile() {
	normal_profile

	# Enable battery saver module
	[ -f /sys/module/battery_saver/parameters/enabled ] && {
		if grep -qo '[0-9]\+' /sys/module/battery_saver/parameters/enabled; then
			apply 1 /sys/module/battery_saver/parameters/enabled
		else
			apply Y /sys/module/battery_saver/parameters/enabled
		fi
	}

	# Disable cpu1 to save some power
	apply 0 /sys/devices/system/cpu/cpu1/online

	# eMMC and UFS governor
	for path in /sys/class/devfreq/*.ufshc; do
		apply powersave $path/governor
	done &
	for path in /sys/class/devfreq/mmc*; do
		apply powersave $path/governor
	done &

	# CPU governor
	powersave_cpu_gov="$(cat /data/bypass_chg/powersave_cpu_gov)"
	change_cpu_gov "$powersave_cpu_gov"

	case "$(cat /data/bypass_chg/soc_recognition)" in
	1) mediatek_powersave ;;
	2) snapdragon_powersave ;;
	3) exynos_powersave ;;
	4) unisoc_powersave ;;
	5) tensor_powersave ;;
	6) intel_powersave ;;
	7) tegra_powersave ;;
	esac
}

###################################
# Main Function
###################################

case "$1" in
0) perfcommon ;;
1) performance_profile ;;
2) normal_profile ;;
3) powersave_profile ;;
esac

wait
exit 0
